# Generated by Django 2.1.4 on 2018-12-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_teags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='teags',
            new_name='tags',
        ),
    ]
